stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - F:\email_spam\data\1_data_ingestion
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - F:\email_spam\data\1_data_ingestion
    - src/data_preprocessing.py
    outs:
    - F:\email_spam\data\2.data_preprocessing
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - F:\email_spam\data\2.data_preprocessing
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - F:\email_spam\data\3.feature_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - F:\email_spam\data\3.feature_data
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
# params:
# - dvclive/params.yaml
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step